### ISSUE TITLE
install cross-env

### ISSUE THREAD

**Issue by willybrauner** [atelierdesmedias/atelier-medias.org#26]
permet l'utilisation des env node avec webpack sous windows

**Comment by Frou-HOS** [comment]
@willybrauner hello j'ai fait quelques modif pour que ça compile avec windows. peut-tu me confirmer que ça compile bien sur mac maintenant ?
Le projet compile bien, par contre je n'accède pas au site via l'url fournit par npm run dev -> http://localhost:3000/public/ mais a un browser de fichier ?

**Comment by willybrauner** [comment]
C'est normal, le localhost port 3000 est l'adresse sur laquelle sont servie les assets. Pour visualiser le front, il faut aller sur le chemin direct de ton dossier public. `http://localhost/mon-site/dist/public/`

Je regarde plus tard si tout fonctionne chez moi. 

Pour la suite, pense bien à ne pas travailler sur master directement mais à créer une branch ;)

**Comment by willybrauner** [comment]
@Frou-HOS cross-env ne pose pas de problème chez moi.
